// Parser for intercepted csp_report requests.
export default class CspReport {
    initiator;
    report;
    blockeduri;

    #decodeReportUri(uri) {
        if (uri === "null")
            return null;

        if (uri === "") {
            // Browser redacts the blocked URL for privacy (cross-origin
            // redirects, notably under frame-src). The real scheme is hidden,
            // so represent it as an opaque source.
            return new URL("opaque:");
        }

        // CSP keywords like 'inline' or 'eval' won't parse as URLs without a
        // scheme. Prepending a colon makes them valid opaque URLs (e.g. 'eval:'),
        // which lets the URL constructor succeed and preserves the keyword in
        // the .protocol property for later normalization in ViolationTracker.
        if (CspReport.protocolSource(uri + ":") !== undefined)
            uri += ":";

        try {
            return new URL(uri);
        } catch (e) {
            console.warn("cspreport", "unexpected unparseable uri:", uri, e);
            return null;
        }
    }

    constructor(details) {
        // Decode what chrome is reporting.
        let body = CspReport.#requestBodyDecode(details.requestBody);

        // This is generated by chrome, so assumed well formed.
        this.report = JSON.parse(body)["csp-report"];

        // Convert page into a URL object.
        this.initiator = this.#decodeReportUri(details.initiator);

        // This might also be a URI, or might be a keyword like "inline".
        this.blockeduri = this.#decodeReportUri(this.report["blocked-uri"]);

        console.debug("cspreport", "blocked", this.blocked, "for", this.directive, this);
    }

    static #requestBodyDecode(body) {
        // Shared TextDecoder across all callers of this static method.
        CspReport.#requestBodyDecode._textdec ??= new TextDecoder("utf-8");
        const decoder = CspReport.#requestBodyDecode._textdec;
        let json = "";

        // In theory this could be chunked, but I've never seen that happen.
        for (const {bytes} of body.raw ?? []) {
            if (bytes) json += decoder.decode(bytes, { stream: true });
        }
        return json + decoder.decode();
    }

    get directive() {
        return this.report["effective-directive"];
    }

    get blocked() {
        return this.blockeduri;
    }

    // CSP report's "blocked-uri" can be a real URL or a pseudo-scheme used
    // by the browser to represent opaque sources (inline scripts, eval,
    // etc). After parsing through new URL(), the .protocol of those
    // pseudo-schemes maps to the CSP source-list keyword that allows them.
    static protocolSource(protocol) {
        switch (protocol) {
            case "inline:":
                return "'unsafe-inline'";
            case "eval:":
                return "'unsafe-eval'";
            case "wasm-eval:":
                return "'wasm-unsafe-eval'";
            case "opaque:":
                // Redacted blocked-uri: real scheme hidden, so allow everything
                // for this directive. Kept in sync with help/sources.json.
                console.warn("cspreport", "redacted blocked-uri, substituting allow-all source");
                return "* data: blob:";
            case "about:":
            case "data:":
            case "blob:":
            case "filesystem:":
            case "trusted-types-sink:":
                return protocol;
        }
    }
}
